name: fastbook
channels:
    - fastai
    - pytorch
    - defaults
dependencies:
  - python>=3.6
  - pytorch>=1.6
  - torchvision
  - pip
  - pip:
    - -r requirements.txt #https://stackoverflow.com/a/68586065/758542
